name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths: 
      - 'src/**'
      - 'public/**'
      - 'package.json'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "petland-web"
          heroku_email: "welldey102@gmail.com"
